metadata: {}
implementation_config:

  reader_config:

    read_gcs_locations:
      class: DataStoreReader
      project: artsnob-1
      kind: 11292020-inverse-cluster-index
      keys_only: False
      destinations:
        - invert_inverse_index

    invert_inverse_index:
      class: IndexFromReverseIndex
      key_to_reverse: idx
      destinations:
        - datastore_writer

  writer_config:

    datastore_writer:
      class: DatastoreWriter
      kind_name: 12122020-cluster-index
      gcs_project: artsnob-1
      project: artsnob-1
      key: data
      ids_key: keys
