metadata: {}
implementation_config:

  reader_config:

    read_gcs_locations:
      class: DataStoreReader
      project: artsnob-1
      kind: scraped-image-data
      keys_only: True
      destinations:
        - random_select

    random_select:
      class: RandomSelections
      N: 10000
      n_cutoff: 100
      destinations:
        - datastore_writer

  writer_config:

    datastore_writer:
      class: DatastoreWriter
      kind_name: 07102020-random_selections
      gcs_project: artsnob-1
      project: artsnob-1
      key: random_data
      ids_key: datastore_keys
