metadata: {}
implementation_config:

  reader_config:

    read_gcs_locations:
      class: DataStoreReader
      project: artsnob-1
      kind: 07032020-images-full-embed
      destinations:
        - flatten_lists

    flatten_lists:
      class: ListFlattener
      key: reader_data
      key_to_flatten: embeddings
      key_to_write: data
      destinations:
        - umap_reduction
        - annoy_transformer
        - datastore_writer

    umap_reduction:
      class: UmapPipeline
      is_training: True
      n_components: 100
      destinations:
        - annoy_transformer
        - entity_formatter

    annoy_transformer:
      class: AnnoyPipeline
      is_training: True
      metric: angular
      num_trees: 2500
      n_neighbors: 100
      destinations:
        - entity_formatter

    entity_formatter:
      class: EntityFormatter
      property_keys:
        - umap_data
        - neighbors
      destinations:
        - datastore_writer

  writer_config:

    datastore_writer:
      class: DatastoreWriter
      kind_name: 07062020-pca-nn
      gcs_project: artsnob-1
      key: entities
      project: artsnob-1
      ids_key: key_list
      exclude_from_indexes:
        - index_data
        - umap_data
