runtime: python37

instance_class: F4_1G

service: image-api

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

# network:
#     forwarded_ports:
#         - 8000/tcp

inbound_services:
  - warmup
  
automatic_scaling:
  min_instances: 1

entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app