name: Build Images

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build-scraper
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to gcloud registry
      id: gcloud
      uses: elgohr/gcloud-login-action@master
      with:
        account_key: ${{ secrets.GCLOUD_KEY }}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: art_snob_scrape/repository
        username: ${{ steps.gcloud.outputs.username }}
        password: ${{ steps.gcloud.outputs.password }}
        registry: gcr.io
        dockerfile: art_snob_scrape/Dockerfile

